CREATE SEQUENCE CONTATOS2_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_CONTATOS2 (
    ID INTEGER DEFAULT CONTATOS2_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO VARCHAR(20) NOT NULL
);